// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Zl3zM72Egh34Y_y7K3Lh8FmkgL6yCZ8',
    appId: '1:712914171808:web:6e3947861512d0a810d6c5',
    messagingSenderId: '712914171808',
    projectId: 'donatelife-b1088',
    authDomain: 'donatelife-b1088.firebaseapp.com',
    storageBucket: 'donatelife-b1088.firebasestorage.app',
    measurementId: 'G-N5H2FLS1ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7YHih27Q5bzhW3UYoCbl8rtQVJTTzXX0',
    appId: '1:712914171808:android:620f2ad69112f2bf10d6c5',
    messagingSenderId: '712914171808',
    projectId: 'donatelife-b1088',
    storageBucket: 'donatelife-b1088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSoY6ebH95_p_g9T2l-jqeKEX-CVIWFsg',
    appId: '1:712914171808:ios:0e7505a5f018b9ac10d6c5',
    messagingSenderId: '712914171808',
    projectId: 'donatelife-b1088',
    storageBucket: 'donatelife-b1088.firebasestorage.app',
    iosBundleId: 'com.example.donatelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSoY6ebH95_p_g9T2l-jqeKEX-CVIWFsg',
    appId: '1:712914171808:ios:0e7505a5f018b9ac10d6c5',
    messagingSenderId: '712914171808',
    projectId: 'donatelife-b1088',
    storageBucket: 'donatelife-b1088.firebasestorage.app',
    iosBundleId: 'com.example.donatelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Zl3zM72Egh34Y_y7K3Lh8FmkgL6yCZ8',
    appId: '1:712914171808:web:c703d84e3e4084c810d6c5',
    messagingSenderId: '712914171808',
    projectId: 'donatelife-b1088',
    authDomain: 'donatelife-b1088.firebaseapp.com',
    storageBucket: 'donatelife-b1088.firebasestorage.app',
    measurementId: 'G-MNZQKE25YN',
  );
}
